export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const ID_TYPES = [
  {
    id: "aadhaar",
    label: "Aadhaar Card",
    hint: "12-digit unique ID (e.g. 5432 1098 7654)",
    example: "543210987654",
  },
  {
    id: "pan",
    label: "PAN Card",
    hint: "10-character alphanumeric code (e.g. ABCDE1234F)",
    example: "ABCDE1234F",
  },
  {
    id: "driving_license",
    label: "Driving License",
    hint: "Valid state DL identification number",
    example: "DL-1420110012345",
  },
  {
    id: "passport",
    label: "Indian Passport",
    hint: "8-character passport identifier",
    example: "Z1234567",
  },
  {
    id: "voter_id",
    label: "Voter ID (EPIC)",
    hint: "10-character voter identity card number",
    example: "ABC1234567",
  },
] as const;

export const OWNER_DECLARATIONS = [
  {
    id: "authenticity",
    title: "Outfit Authenticity & Ownership",
    desc: "I declare that all wedding and festive outfits I list on ShaadiRent are authentic, legitimately owned by me, and free from any legal disputes or third-party encumbrances.",
  },
  {
    id: "hygiene",
    title: "Cleanliness & Condition Standards",
    desc: "I agree that all garments will be professionally cleaned, steamed, and in pristine rentable condition before handover or dispatch to renters.",
  },
  {
    id: "pricing_commission",
    title: "Marketplace Commission & Payouts",
    desc: "I acknowledge that ShaadiRent deducts a 15% platform fee from completed rentals for logistics, insurance coordination, and payment processing.",
  },
  {
    id: "true_information",
    title: "Accuracy of Submitted Documents",
    desc: "I certify that all personal information, contact numbers, residential address, and government identification documents uploaded in this application are genuine and accurate.",
  },
] as const;
